version: '3'
services:
  postgresql:
    image: 'postgres'
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  zookeeper:
    image: wurstmeister/zookeeper
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  kafka:
    image: wurstmeister/kafka
    ports:
      - "29092:29092"
      - "19092:19092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_LISTENERS: 'ISSL://localhost:29092,OSSL://kafka:19092,PLAINTEXT://localhost:9092'
      KAFKA_LISTENERS: 'ISSL://:29092,OSSL://:19092,PLAINTEXT://:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'ISSL:SSL,OSSL:SSL,PLAINTEXT:PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_SSL_ENABLED_PROTOCOLS: 'TLSv1.2,TLSv1.3,TLSv1.1'
      KAFKA_SSL_PROTOCOL: 'TLSv1.2'
      KAFKA_SSL_KEYSTORE_LOCATION: '/certs/kafka.server.keystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: 'maciek'
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_KEY_PASSWORD: 'maciek'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/certs/kafka.server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 'maciek'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
    volumes:
      - ./ssl2:/certs
    depends_on:
      - zookeeper
  springboot:
    container_name: springboot
    image: spring
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - zookeeper
      - kafka

  react:
    restart: always
    container_name: react
    image: react
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - springboot

  mission-manager:
    image: mission-manager
    network_mode: "host"
  sitl:
    image: wnt3rmute/ardupilot-sitl
    network_mode: "host"
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
    # Possible options: --console, --map, -L <location>
    # ParkVision custom locations: Legnicka, Janiszewskiego, Wronskiego
    command: ./sim_vehicle.py -l 51.10891,17.05562,120,0 --map -v ArduCopter -N