spring:
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://ep-wandering-snow-036542.eu-central-1.aws.neon.tech/neondb
    username: filipshelby
    password: H2vCI4gEXrDk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: parkvision.info@gmail.com
    password: zzwbdafgndoappdy
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
stripe:
  key:
    publishable: pk_test_51O7dhAIrZoSsqF8FSsocK5PN6flQu4RqAA4h6iU5VMXv2BPBelaOBgKESYUTsJAZZXXOFh5982g9YbK4Lf5I5UIw00m4QsipIP
    secret: sk_test_51O7dhAIrZoSsqF8F3LIcn6BlsxTxFk4n9PftCY9WFwuULCEtnGja8oPTI8YwT0fGSY9mu82hLlqJMEdyqOxsXroK002KIRuft5
park-vision:
  hour-rule: 2