-- DROP ALL TABLES ALONG WITH CASCADE
TRUNCATE TABLE  reservation;
TRUNCATE TABLE  payment;
TRUNCATE TABLE  point;
TRUNCATE TABLE  drone;
TRUNCATE TABLE  drone_mission;
TRUNCATE TABLE  car;
TRUNCATE TABLE  _user;
TRUNCATE TABLE  parking_spot;
TRUNCATE TABLE  parking;
