-- DROP ALL TABLES ALONG WITH CASCADE
DROP TABLE IF EXISTS reservation CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS point CASCADE;
DROP TABLE IF EXISTS drone CASCADE;
DROP TABLE IF EXISTS drone_mission CASCADE;
DROP TABLE IF EXISTS car CASCADE;
DROP TABLE IF EXISTS _user CASCADE;
DROP TABLE IF EXISTS parking_spot CASCADE;
DROP TABLE IF EXISTS parking CASCADE;
